#!/bin/sh

config=$1

if test "x$config" = "x" ; then
  config="dev"
fi

deps=
for d in deps/* ; do
  deps="$deps -pa $d/ebin"
done

exec erl \
  -name opentsdb_$config -setcookie opentsdb \
  $deps \
  -pa ebin \
  -config conf/mondemand_server_$config.config \
  -eval "[ application:start(A) || A <- [syntax_tools, compiler, goldrush, lager ]], reloader:start(), mondemand_server_app:start()."
